  function Patatp()
      % Patatp - Brief description
      %
      % Syntax: Patatp()
      %
      % This is a stub function generated by the Setup Wizard.
      % Replace this content with your actual implementation.

      % Your code here
      disp('Patatp function executed');

  end