  function adfafa()
      % adfafa - Brief description
      %
      % Syntax: adfafa()
      %
      % This is a stub function generated by the Setup Wizard.
      % Replace this content with your actual implementation.

      % Your code here
      disp('adfafa function executed');

  end