  function alfabe()
      % alfabe - Brief description
      %
      % Syntax: alfabe()
      %
      % This function was generated by the Setup Wizard.
      % It includes automatic loading of input data from a .mat file.
      %
      % Input file: test_data.mat

      fprintf('Starting alfabe...\n');

      % Load input data if file path is provided
      inputFilePath = 'test_data.mat';

      if ~isempty(inputFilePath)
          fprintf('Loading data from: %s\n', inputFilePath);

          try
              % Load the .mat file
              data = load(inputFilePath);
              fprintf('Data loaded successfully!\n');

              % Display variables in the loaded file
              varNames = fieldnames(data);
              fprintf('Variables loaded: ');
              fprintf('%s ', varNames{:});
              fprintf('\n');

              % YOUR CODE HERE
              % Access loaded variables using: data.variableName
              % Example: myVariable = data.myVariable;

          catch ME
              fprintf('Error loading file: %s\n', ME.message);
              return;
          end
      else
          fprintf('No input file specified. Running without input data.\n');
          % YOUR CODE HERE for cases without input file
      end

      fprintf('alfabe execution completed.\n');

  end